import 'package:meta/meta.dart';

import '../package_dependency.dart';
import '../sdk_dependency.dart';

String formatToYaml({
  @required Iterable<SdkDependency> sdks,
  @required Iterable<PackageDependency> packages,
}) =>
    '''
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
${_formatSdkDependencies(sdks)}''';

String _formatSdkDependencies(Iterable<SdkDependency> sdks) => '''
sdks:${sdks.map((sdk) => "\n  ${sdk.sdk}: \"${sdk.version}\"").join()}
''';
